apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
  - name: database
    image: redis
    ports:
    - containerPort: 8080
  tolerations:
    - key: "memory"
      operator: "Equal"
      value: "large"
      effect: "NoSchedule"
        