apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      run: webserver
  replicas: 4
  template:
    metadata:
      labels:
        run: webserver
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
        - key: "memory"
          operator: "Equal"
          value: "large"
          effect: "NoSchedule"
