apiVersion: v1
kind: Service
metadata:  
  name: nodeportservice
spec:
  selector:    
    app: webserver
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP

