apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - east          
  containers:
  - name: httpd
    image: httpd
    
