apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      run: database
  replicas: 4
  template:
    metadata:
      labels:
        run: database
    spec:
      containers:
      - name: database
        image: redis
        ports:
        - containerPort: 80
      tolerations:
        - key: "platform"
          operator: "Equal"
          value: "sandbox"
          effect: "NoSchedule"