apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: db
  replicas: 3
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: database
        image: redis
        ports:
        - containerPort: 8080
      nodeSelector:
        diskType: ssd

